#!/usr/bin/env python3
"""Make a chunky little pixel-cougar mascot (Claude-Code-style) from the main
logo, rendered as half-block rows so it stays crisp at tiny size.

Emits sprite.ts with SPRITE_MAIN (array of strings) + width, for the TUI to
print in the Cougar red. Half-block chars (space, upper, lower, full) let each
text cell hold 2 vertical pixels, doubling vertical resolution."""
import subprocess
import os
import sys
import json
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SVG = os.path.join(HERE, "logos", "main.svg")
RASTER = "/tmp/main_raster.png"
COLS = int(sys.argv[1]) if len(sys.argv) > 1 else 14  # sprite width in cells

# rasterize the SVG fresh (transparent) via chromium
subprocess.run([
    "chromium-browser", "--headless", "--disable-gpu",
    "--force-device-scale-factor=1", "--default-background-color=00000000",
    "--hide-scrollbars", "--window-size=400,458",
    "--screenshot=" + RASTER, "file://" + SVG,
], check=True, stderr=subprocess.DEVNULL)

im = Image.open(RASTER).convert("RGBA")
alpha = im.split()[3]
w, h = im.size
rows2 = round(COLS * (h / w))          # vertical pixels (2 per text row)
if rows2 % 2:
    rows2 += 1
small = alpha.resize((COLS, rows2), Image.BILINEAR)
px = small.load()
THR = 90

# Carve a little mouth: the logo has only eyes + nose, so at this size there's
# nothing mouth-like. Punch an inverted-triangle notch (wide at top, narrowing
# to a point) into the lower muzzle so the mascot reads as a face / muzzle.
mw = max(4, COLS // 4)          # mouth width at the top, in pixels
mh = max(3, mw - 1)             # mouth height in pixels
my = int(rows2 * 0.72)          # top of the mouth, on the lower muzzle
for i in range(mh):
    w = round(mw * (mh - i) / mh)   # taper to a point
    if w <= 0:
        break
    mx = (COLS - w) // 2
    yy = my + i
    for xx in range(mx, mx + w):
        if 0 <= xx < COLS and 0 <= yy < rows2:
            small.putpixel((xx, yy), 0)
px = small.load()

UPPER, LOWER, FULL, BLANK = "▀", "▄", "█", " "

lines = []
for r in range(0, rows2, 2):
    line = ""
    for c in range(COLS):
        top = px[c, r] > THR
        bot = px[c, r + 1] > THR if r + 1 < rows2 else False
        line += FULL if (top and bot) else UPPER if top else LOWER if bot else BLANK
    lines.append(line)  # keep width fixed

# preview to console
for ln in lines:
    print("|" + ln + "|")

ts = (
    "// GENERATED by gen_sprite.py - do not hand-edit.\n"
    "// A miniaturized pixel-cougar mascot (half-block rows), from logos/main.svg.\n"
    "export const SPRITE_MAIN: string[] = [\n"
    + "".join('  %s,\n' % json.dumps(ln, ensure_ascii=False) for ln in lines)
    + "]\n"
    "export const SPRITE_MAIN_WIDTH = %d\n" % COLS
)
with open(os.path.join(HERE, "sprite.ts"), "w") as f:
    f.write(ts)
print("wrote sprite.ts (%d x %d rows)" % (COLS, len(lines)))
